### ISSUE TITLE
Upgrade the PWA Guide to use Google WorkBox

### ISSUE THREAD

**Issue by mahmoudrabie** [vincentmorneau/apex-pwa#14]
Dear Vincent

To simplify adding PWA support to Oracle APEX, I would suggest to upgrade the [**guide**](http://vmorneau.me/apex-pwa/) to use Google [**WorkBox**](https://developers.google.com/web/tools/workbox/)

What is your opinion?

Regards
Mahmoud

**Comment by vincentmorneau** [comment]
The guide is about explaining the native APIs that makes PWAs. WorkBox sounds like a good project, but it was not the intent of the APEX PWA guide to hide the PWA logic behind a framework.

**Comment by mahmoudrabie** [comment]
Thanks a lot.
