### ISSUE TITLE
add sw.js  in shared components

### ISSUE THREAD

**Issue by kerrybad** [vincentmorneau/apex-pwa#7]
Good Day,

im very excited to get test out your push notifications.

I wanted to ask how can i register my my sw.js file?,If i uploaded it to my applications shared components?

i tried .register('#APP_IMAGES.sw.js') , but i am getting an error "Service worker failed to register. DOMException"

I do not have any access to root files.

Thank you for your help in advanced.

Thanks,
Kerry

**Comment by vincentmorneau** [comment]
Hi Kerry,

As the documentation indicates, it is not possible to register a service worker from the APP_IMAGES.

If your business requires push notifications, you should have no trouble demanding for root access :) Or ask a DBA to drop the sw.js there for you.

Good luck.

**Comment by kerrybad** [comment]
Thank you, i have been given some access :)
